Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -10,26 +10,28 @@ jobs:
           submodules: recursive
 
       - name: Install iverilog
-        shell: bash
-        run: sudo apt-get update && sudo apt-get install -y iverilog
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y iverilog
 
-      # Set Python up and install cocotb
       - name: Setup python
         uses: actions/setup-python@v5
         with:
           python-version: '3.11'
 
       - name: Install Python packages
-        shell: bash
         run: pip install -r test/requirements.txt
 
       - name: Run tests
+        working-directory: test
         run: |
-          cd test
           make clean
           make
-          # make will return success even if the test fails, so check for failure in the results.xml
-          ! grep failure results.xml
+          # Check if the test failed by searching the results.xml for failure
+          if grep -q "<failure" results.xml; then
+            echo "Test failures detected!"
+            exit 1
+          fi
 
       - name: Test Summary
         uses: test-summary/action@v2.3
@@ -37,11 +39,11 @@ jobs:
           paths: "test/results.xml"
         if: always()
 
-      - name: upload vcd
-        if: success() || failure()
+      - name: Upload VCD and results
+        if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: test-vcd
+          name: test-artifacts
           path: |
             test/tb.vcd
             test/results.xml
